### PR TITLE
[BUG] Fix resource leaks in command and query handlers

### LINKED ISSUE #63: [BUG] Fix resource leaks in command and query handlers
## Desired Solution
The current `query` and `command` handler codebase has a resource leak due to a missing request body close call.

## Suggested Implementation
Please add the missing `defer r.Body.Close()` function call to each handler.

- HTTP connections are persistent by default, and failing to close r.Body can cause resource exhaustion (e.g., too many open files).
- Some HTTP clients may wait for the body to be consumed or closed, causing slow request handling.
- If the request body is not closed, the connection might remain open until it times out.

## Testing
Please ensure that the current state of unit tests remains unbroken after modification.

### PR DESCRIPTION
**Pull request by ac4ch**
## Description of Changes

Provide a brief description of the changes you've made.

## Linked Issues / Tickets

Reference any related issues or tickets, e.g. "Closes #123".

## Testing Procedure

Describe the tests you've added or any testing steps you've taken.

- [ ] I have added new unit tests
- [ ] All tests pass locally
- [ ] I have tested manually in my local environment

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have run the linter

### CODE REVIEW

File: pkg/server/http.go [hunk 1]
```diff
@@ -51,6 +51,26 @@ func WithMongo() HTTPOption {
 	}
 }
 
+// WithBodyClose is a middleware that ensures the request body is closed after processing.
+// This is important for memory management and preventing resource leaks.
+// It is particularly useful when using http.HandlerFunc to handle requests.
+func WithBodyClose(h http.HandlerFunc) http.HandlerFunc {
+	return func(w http.ResponseWriter, r *http.Request) {
+		defer func() {
+			_ = r.Body.Close()
```
Comment (mgosek-4chain) [inline pkg/server/http.go]: Since it's still under development, maybe we should at least add error logging :)

Comment (ac4ch) [reply pkg/server/http.go]: sure :)

**Review by mgosek-4chain — APPROVED** [review]
