### PR TITLE
BUG(request_sync_response) : add header validation for x-bsv-topic

### LINKED ISSUE #112: [BUG] Add missing X-Bsv-Topic header check in RequestSyncResponseHandler
## Desired Solution
 
Please add the missing header check during request processing, in accordance with:
 https://github.com/bitcoin-sv/overlay-example/blob/master/src/index.ts#L303

## Suggested Implementation

Return http status code 400 with the appropriate error message.

### PR DESCRIPTION
**Pull request by cain4chain**
## Description of Changes

chore(x-bsv-topic) : add custom header for topic value and replace query params

## Linked Issues / Tickets

closes https://github.com/4chain-ag/go-overlay-services/issues/112

## Testing Procedure

chore(resquest_sync_response_test) : updated test cases using the header validation

- [ ] I have added new unit tests
- [ ] All tests pass locally
- [ ] I have tested manually in my local environment

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have run the linter

### CODE REVIEW

File: pkg/server/internal/app/commands/request_sync_response.go [hunk 1]
```diff
@@ -34,9 +34,9 @@ func (h *RequestSyncResponseHandler) Handle(w http.ResponseWriter, r *http.Reque
 		return
 	}
 
-	topic := r.URL.Query().Get("topic")
+	topic := r.Header.Get("x-bsv-topic")
 	if topic == "" {
-		http.Error(w, "missing 'topic' query parameter", http.StatusBadRequest)
+		http.Error(w, "missing 'x-bsv-topic' header", http.StatusBadRequest)
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response.go]: Please extract the string into an exported error type: 

```
// ErrMissingXBSVTopicHeader ....
var ErrMissingXBSVTopicHeader = errors.New("missing 'x-bsv-topic' header")
```

File: pkg/server/internal/app/commands/request_sync_response_test.go [hunk 2]
```diff
@@ -49,7 +49,12 @@ func TestRequestSyncResponseHandler_Success(t *testing.T) {
 	require.NoError(t, err)
 
 	// When:
-	resp, err := ts.Client().Post(ts.URL+"?topic=example-topic", "application/json", bytes.NewReader(body))
+	req, err := http.NewRequest(http.MethodPost, ts.URL, bytes.NewReader(body))
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response_test.go]:
```
req, err := http.NewRequest(http.MethodPost, ts.URL, testutil.RequestBody(t, payload))
```

File: pkg/server/internal/app/commands/request_sync_response_test.go [hunk 3]
```diff
@@ -73,7 +78,11 @@ func TestRequestSyncResponseHandler_MissingTopic(t *testing.T) {
 	require.NoError(t, err)
 
 	// When:
-	resp, err := ts.Client().Post(ts.URL, "application/json", bytes.NewReader(body))
+	req, err := http.NewRequest(http.MethodPost, ts.URL, bytes.NewReader(body))
+	require.NoError(t, err)
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response_test.go:84]:
```
req, err := http.NewRequest(http.MethodPost, ts.URL, testutil.RequestBody(t, payload))
```

File: pkg/server/internal/app/commands/request_sync_response_test.go [hunk 4]
```diff
@@ -82,7 +91,7 @@ func TestRequestSyncResponseHandler_MissingTopic(t *testing.T) {
 
 	respBody, err := io.ReadAll(resp.Body)
 	require.NoError(t, err)
-	require.Contains(t, string(respBody), "missing 'topic'")
+	require.Contains(t, string(respBody), "missing 'x-bsv-topic'")
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response_test.go]:
```
	actualErr := testutil.ParseToError(t, resp.Body)
	require.Equal(t, http.StatusBadRequest, resp.StatusCode)
	require.Equal(t, commands.ErrMissingXBSVTopicHeader, actualErr)
```

File: pkg/server/internal/app/commands/request_sync_response_test.go [hunk 5]
```diff
@@ -93,7 +102,12 @@ func TestRequestSyncResponseHandler_InvalidJSON(t *testing.T) {
 	defer ts.Close()
 
 	// When:
-	resp, err := ts.Client().Post(ts.URL+"?topic=example-topic", "application/json", bytes.NewReader([]byte(`{invalid-json}`)))
+	req, err := http.NewRequest(http.MethodPost, ts.URL, bytes.NewReader([]byte(`{invalid-json}`)))
+	require.NoError(t, err)
+	req.Header.Set("Content-Type", "application/json")
+	req.Header.Set("x-bsv-topic", "example-topic")
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response_test.go]:
```
	req, err := http.NewRequest(http.MethodPost, ts.URL, testutil.RequestBody(t, `{invalid-json}`))
	require.NoError(t, err)

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-bsv-topic", "example-topic")
```

File: pkg/server/internal/app/commands/request_sync_response_test.go [hunk 6]
```diff
@@ -117,7 +131,12 @@ func TestRequestSyncResponseHandler_InternalServerError(t *testing.T) {
 	require.NoError(t, err)
 
 	// When:
-	resp, err := ts.Client().Post(ts.URL+"?topic=example-topic", "application/json", bytes.NewReader(body))
+	req, err := http.NewRequest(http.MethodPost, ts.URL, bytes.NewReader(body))
+	require.NoError(t, err)
+	req.Header.Set("Content-Type", "application/json")
+	req.Header.Set("x-bsv-topic", "example-topic")
```
Comment (mgosek-4chain) [inline pkg/server/internal/app/commands/request_sync_response_test.go]:
```
	req, err := http.NewRequest(http.MethodPost, ts.URL, testutil.RequestBody(t, `{invalid-json}`))
	require.NoError(t, err)

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-bsv-topic", "example-topic")
```

I would recommend creating an exported const with defined header to avoid code duplication :)

**Review by mgosek-4chain — APPROVED** [review]
